# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevin/PongGame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevin/PongGame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/PongGame/CMakeFiles /home/kevin/PongGame//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin/PongGame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PongGame

# Build rule for target.
PongGame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PongGame
.PHONY : PongGame

# fast build rule for target.
PongGame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/build
.PHONY : PongGame/fast

Game/Ball.o: Game/Ball.cpp.o
.PHONY : Game/Ball.o

# target to build an object file
Game/Ball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Ball.cpp.o
.PHONY : Game/Ball.cpp.o

Game/Ball.i: Game/Ball.cpp.i
.PHONY : Game/Ball.i

# target to preprocess a source file
Game/Ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Ball.cpp.i
.PHONY : Game/Ball.cpp.i

Game/Ball.s: Game/Ball.cpp.s
.PHONY : Game/Ball.s

# target to generate assembly for a file
Game/Ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Ball.cpp.s
.PHONY : Game/Ball.cpp.s

Game/Game.o: Game/Game.cpp.o
.PHONY : Game/Game.o

# target to build an object file
Game/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Game.cpp.o
.PHONY : Game/Game.cpp.o

Game/Game.i: Game/Game.cpp.i
.PHONY : Game/Game.i

# target to preprocess a source file
Game/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Game.cpp.i
.PHONY : Game/Game.cpp.i

Game/Game.s: Game/Game.cpp.s
.PHONY : Game/Game.s

# target to generate assembly for a file
Game/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Game.cpp.s
.PHONY : Game/Game.cpp.s

Game/Indicator.o: Game/Indicator.cpp.o
.PHONY : Game/Indicator.o

# target to build an object file
Game/Indicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Indicator.cpp.o
.PHONY : Game/Indicator.cpp.o

Game/Indicator.i: Game/Indicator.cpp.i
.PHONY : Game/Indicator.i

# target to preprocess a source file
Game/Indicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Indicator.cpp.i
.PHONY : Game/Indicator.cpp.i

Game/Indicator.s: Game/Indicator.cpp.s
.PHONY : Game/Indicator.s

# target to generate assembly for a file
Game/Indicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Indicator.cpp.s
.PHONY : Game/Indicator.cpp.s

Game/Paddle.o: Game/Paddle.cpp.o
.PHONY : Game/Paddle.o

# target to build an object file
Game/Paddle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Paddle.cpp.o
.PHONY : Game/Paddle.cpp.o

Game/Paddle.i: Game/Paddle.cpp.i
.PHONY : Game/Paddle.i

# target to preprocess a source file
Game/Paddle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Paddle.cpp.i
.PHONY : Game/Paddle.cpp.i

Game/Paddle.s: Game/Paddle.cpp.s
.PHONY : Game/Paddle.s

# target to generate assembly for a file
Game/Paddle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Paddle.cpp.s
.PHONY : Game/Paddle.cpp.s

Game/PlayerScore.o: Game/PlayerScore.cpp.o
.PHONY : Game/PlayerScore.o

# target to build an object file
Game/PlayerScore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/PlayerScore.cpp.o
.PHONY : Game/PlayerScore.cpp.o

Game/PlayerScore.i: Game/PlayerScore.cpp.i
.PHONY : Game/PlayerScore.i

# target to preprocess a source file
Game/PlayerScore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/PlayerScore.cpp.i
.PHONY : Game/PlayerScore.cpp.i

Game/PlayerScore.s: Game/PlayerScore.cpp.s
.PHONY : Game/PlayerScore.s

# target to generate assembly for a file
Game/PlayerScore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/PlayerScore.cpp.s
.PHONY : Game/PlayerScore.cpp.s

Game/Vec2.o: Game/Vec2.cpp.o
.PHONY : Game/Vec2.o

# target to build an object file
Game/Vec2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Vec2.cpp.o
.PHONY : Game/Vec2.cpp.o

Game/Vec2.i: Game/Vec2.cpp.i
.PHONY : Game/Vec2.i

# target to preprocess a source file
Game/Vec2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Vec2.cpp.i
.PHONY : Game/Vec2.cpp.i

Game/Vec2.s: Game/Vec2.cpp.s
.PHONY : Game/Vec2.s

# target to generate assembly for a file
Game/Vec2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/Game/Vec2.cpp.s
.PHONY : Game/Vec2.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PongGame.dir/build.make CMakeFiles/PongGame.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PongGame"
	@echo "... Game/Ball.o"
	@echo "... Game/Ball.i"
	@echo "... Game/Ball.s"
	@echo "... Game/Game.o"
	@echo "... Game/Game.i"
	@echo "... Game/Game.s"
	@echo "... Game/Indicator.o"
	@echo "... Game/Indicator.i"
	@echo "... Game/Indicator.s"
	@echo "... Game/Paddle.o"
	@echo "... Game/Paddle.i"
	@echo "... Game/Paddle.s"
	@echo "... Game/PlayerScore.o"
	@echo "... Game/PlayerScore.i"
	@echo "... Game/PlayerScore.s"
	@echo "... Game/Vec2.o"
	@echo "... Game/Vec2.i"
	@echo "... Game/Vec2.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

